apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluentd.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Fetching logs from DEFAULT CONTAINER FOLDER (ON NODE) AND PARSING
    <source>
      @type tail
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      # time_format %Y-%m-%d %H:%M:%S,%L
      # time_format %Y-%m-%dT%H:%M:%S.%NZ
      # format none
      # tag file.logs
      <parse>
        @type regexp
        expression /^(?<message>.+)(?<blog_msg>\{[^\}]+\})/
        # expression /^(?<message>.+)/
        time_format %Y-%m-%d %H:%M:%S,%L
      </parse>
      read_from_head true
    </source>

    # <filter kubernetes.**>
    #   @type kubernetes_metadata
    # </filter>

    # <filter kubernetes.**>
    #   @type parser
    #   key_name message
    #   reserve_data true
    #   hash_value_field parsed_message
    #   <parse>
    #     @type json
    #   </parse>
    # </filter>

    # <filter kubernetes.**>
    #   @type parser
    #   key_name message
    #   reserve_data true
    #   <parse>
    #     @type regexp
    #     expression /"message":"(?<parsed_json>{[^}]+})"/
    #   </parse>
    # </filter>

    # <filter kubernetes.**>
    #   @type record_transformer
    #   enable_ruby true
    #   <record>
    #     parsed_json ${record["parsed_json"]}
    #   </record>
    #   # remove_keys parsed_message
    # </filter>

    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    # <match **>
    #   @type elasticsearch
    #   @log_level info
    #   host elasticsearch.elastic.svc.cluster.local
    #   port 9200
    #   scheme http
    #   index_name fluentd
    #   type_name _doc
    #   logstash_format true
    #   logstash_prefix logstash
    #   include_tag_key true
    #   tag_key @log_name
    #   reconnect_on_error true
    #   <buffer>
    #     @type file
    #     path /var/log/fluentd-buffers/kubernetes.system.buffer
    #     flush_mode interval
    #     retry_type exponential_backoff
    #     flush_thread_count 2
    #     flush_interval 5s
    #     retry_forever
    #     retry_max_interval 30
    #     chunk_limit_size 2M
    #     queue_limit_length 8
    #     overflow_action block
    #   </buffer>

    <match kubernetes.**>
      @type stdout
    </match>

